### ISSUE TITLE
Game engine. To use one or not.

### ISSUE THREAD

**Issue by valera-rozuvan** [valera-rozuvan/bbzfc#1]
Possible engines to use:
1. [Unreal Engine 4](https://www.unrealengine.com/unreal-engine-4)
2. [UNITY 5](https://unity3d.com/)
3. [OGRE](http://www.ogre3d.org/about)
4. ?

Or we should start from scratch, and develop our own solution?

Please have in mind that we also want to target Mobile platforms...

**Comment by valera-rozuvan** [comment]
As suggested by **Mannfred** in an e-mail to me:

> Do it modular, use an existing engine like unity3d or the unreal engine.
> - This decreases the time needed about 2 orders of magnitude.
> - If there is a problem/ bug, there is already a community dealing with it.
> 
> Use the assets those gaming engines offer
> - You need a radar? player handling? GUI? there are already assets which can easily be implemented.
> - This also reduces the development time.

**Comment by valera-rozuvan** [comment]
So, I have been playing around with Unity 3D. I was quite pleasantly surprised by how easy it was to create a mock up tank like "game" (just a single object in a world, that can move), and make it compile under Linux and Windows from the same source tree.

= )

Also, making Unity 3D run under latest Ubuntu is not such a chore after all! The key thing is that your video card + drivers setup must support OpenGL 3.3 (and above).

I guess I will outline the setup process on the GitHub repository, and commit my simple mock up game there also.

I will be pushing forwards with the idea that The Clone (tm) should be made with Unity 3D = )

**Comment by kaadmy** [comment]
Have you tried using Godot or Urho3D? Ther're both good engines, but they require coding experience. Urho3D uses C++, while Godot uses a Python-like scripting language.

**Comment by valera-rozuvan** [comment]
@kaadmy Yes. I have seen those engines. I don't see a problem with using them. However, the time to create something playable will be much bigger if we decide to use them. Prove me wrong if you can = )

The appeal to Unity3D is the quick development possibility!

**Comment by kaadmy** [comment]
Yep. But using engines like Urho3D may result in far lower hardware requirements and higher performance.
